### PR TITLE
Bump CoffeeScript version

### PR DESCRIPTION
**Pull request by crazymykl**
This lets users use ES6 modules without backticks and without tons of errors.

### CODE REVIEW

**Comment by crazymykl** [comment]
Fixes #26 .

**Comment by crazymykl** [comment]
I would like see this get some attention, I don't want to have to disable linting to get module support.

**Comment by chrishulton** [comment]
Hi @crazymykl, thanks for the nudge.  We haven't updated this engine in a while so I made a few other maintenance changes in this PR: https://github.com/codeclimate/codeclimate-coffeelint/pull/28

I upgraded the engine's coffeelint dependency to `1.16.0` which also bumped the coffeescript version to `1.11.1`.  Let me know if this fixes the issue for you.

**Comment by crazymykl** [comment]
Yep, that worked. Is there a plan to have a config (or separate engine) for coffeescript v2 when it comes out?

**Comment by chrishulton** [comment]
We don't have a specific plan yet. One possibility would be to add v2 as a separate channel in this engine.  For instance, you could then specify in your Code Climate config:
```
  coffeelint:
    enabled: true
    channel: coffeescript-v2
```
if you wanted to use v2, similar to what is done in the eslint engine.

**Pull request closed without merging**
