### PR TITLE
Return No Results if there are no Analyzable files.

### PR DESCRIPTION
**Pull request by kalmbach**
When running this engine from the codeclimate cli to analyze a single
file, if the file is not analyzable the coffeelint engine throws the
following error:

> Running coffeelint: Done!
> error: (CC::Analyzer::Engine::EngineFailure) engine coffeelint failed
> with status 1

The current fix prevents the engine of parsing non existing results when
running against a file that is not analyzable.

Added a spec in coffeelint_spec to validate this.

### CODE REVIEW

**Comment by pbrisbin** [comment]
Thanks @kalmbach, this LGTM. I'm going to make a change to master so that the Circle build works for forks. Once that's done, I might ask you to rebase so we can see green before merging.

**Comment by pbrisbin** [comment]
OK, the fixes to `circle.yml` were merged. If you rebase, we should see a green build.

**Comment by kalmbach** [comment]
:( still failing.

**Comment by pbrisbin** [comment]
Doh, sorry about that. Fix coming.

**Comment by pbrisbin** [comment]
OK, hopefully really fixed now. Sorry for the false-starts. If it still errors I'll either merge anyway, or handle the git stuff myself. Thanks again for the contribution!

**Comment by kalmbach** [comment]
\o/ yay!

**Comment by pbrisbin** [comment]
Merged as 9b17fab3

**Pull request closed without merging**
